### ISSUE TITLE
README says the space converts to " "*8 but lib and tests to " "*7

### ISSUE THREAD

**Issue by Nakilon** [xuanxu/telegraph#2]

**Comment by xuanxu** [comment]
Thanks for spotting this @Nakilon! 
The docs [have been updated](https://github.com/xuanxu/telegraph/commit/62f6963fe5fee13e7adef62fdb591c440302c31d) to correctly state that word separator length is 7 spaces, as recommended in the [ITU specs](https://www.itu.int/rec/R-REC-M.1677-1-200910-I)
